###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM=mpicomm
GRAVITY=nogravity
FORCING=noforcing
ENTROPY=noentropy
MAGNETIC=nomagnetic
VISCOSITY=viscosity
HYDRO=hydro
DENSITY=density
SPECIAL = special/klein_gordon
REAL_PRECISION=double
